USE [master]
GO

/****** Object:  Database [salon_krasoty]    Script Date: 21.01.2022 9:37:46 ******/
CREATE DATABASE [salon_krasoty]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'salon_krasoty', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\salon_krasoty.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'salon_krasoty_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\salon_krasoty_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [salon_krasoty].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [salon_krasoty] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [salon_krasoty] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [salon_krasoty] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [salon_krasoty] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [salon_krasoty] SET ARITHABORT OFF 
GO

ALTER DATABASE [salon_krasoty] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [salon_krasoty] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [salon_krasoty] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [salon_krasoty] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [salon_krasoty] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [salon_krasoty] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [salon_krasoty] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [salon_krasoty] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [salon_krasoty] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [salon_krasoty] SET  DISABLE_BROKER 
GO

ALTER DATABASE [salon_krasoty] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [salon_krasoty] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [salon_krasoty] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [salon_krasoty] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [salon_krasoty] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [salon_krasoty] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [salon_krasoty] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [salon_krasoty] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [salon_krasoty] SET  MULTI_USER 
GO

ALTER DATABASE [salon_krasoty] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [salon_krasoty] SET DB_CHAINING OFF 
GO

ALTER DATABASE [salon_krasoty] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [salon_krasoty] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [salon_krasoty] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [salon_krasoty] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [salon_krasoty] SET QUERY_STORE = OFF
GO

ALTER DATABASE [salon_krasoty] SET  READ_WRITE 
GO

